import { Tab, Tabs } from "@nextui-org/react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { LoadingPage } from "~/components/Loading";
import { api } from "~/utils/api";
import RuleEditor from "~/components/RuleEditor";

export default function Rules() {
  const { data, isLoading } = api.post.getAll.useQuery();
  const { data: sessionData } = useSession();

  const { data: isPersonnel, isLoading: isUserLoading } =
    api.user.userIsAdmin.useQuery(
      { id: sessionData?.user.id ?? "" },
      {
        enabled: !!sessionData,
      },
    );

  if (isLoading || isUserLoading) return <LoadingPage />;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Правила</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-1 flex-col">
        <div className="container mt-20 flex flex-1 flex-col">
          <Tabs
            aria-label="tabs"
            variant="underlined"
            classNames={{
              tabList:
                " gap-6 w-full relative rounded-none p-0 border-b border-divider",
              cursor: "w-full bg-[#dc2626]",
              tab: "first:ml-auto max-w-fit px-0 h-12 last:mr-auto md:last:mr-0",
            }}
          >
            <Tab
              key="common"
              title={
                <div className="flex items-center space-x-2">
                  <span className="font-montserrat">Общие правила</span>
                </div>
              }
            >
              <div>ОБЩИЕ ПРАВИЛА</div>
            </Tab>
            <Tab
              key="disciplines"
              title={
                <div className="flex items-center space-x-2">
                  <span className="font-montserrat">Дисциплины</span>
                </div>
              }
            >
              <div>ДИСЦИПЛИНЫ</div>
            </Tab>
            <Tab
              key="rituals"
              title={
                <div className="flex items-center space-x-2">
                  <span className="font-montserrat">Ритуалы</span>
                </div>
              }
            >
              <div>РИТУАЛЫ</div>
            </Tab>
            {!!isPersonnel && (
              <Tab
                key="new_rule"
                title={
                  <div className="flex items-center space-x-2">
                    <span className="font-montserrat">Добавить правило</span>
                  </div>
                }
              >
                <RuleEditor />
              </Tab>
            )}
          </Tabs>
        </div>
      </main>
    </>
  );
}
