import Head from "next/head";
import { useState } from "react";
import ProductCard from "~/components/products/ProductCard";
import CartDrawer from "~/components/products/CartDrawer";
import { api } from "~/utils/api";

export default function Store() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const handleCartIconClick = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };

  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Магазин</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartDrawer isOpen={isDrawerOpen} onCartIconClick={handleCartIconClick} />
      <main className="flex min-h-screen flex-1 flex-col py-24">
        <div className="container grid grid-cols-2 gap-12 md:grid-cols-3 lg:grid-cols-4">
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
          <ProductCard id={"1"} />
        </div>
      </main>
    </>
  );
}
