import Head from "next/head";
import { useState } from "react";
import ProductCard from "~/components/products/ProductCard";
import CartDrawer from "~/components/products/CartDrawer";
import { api } from "~/utils/api";
import { LoadingPage } from "~/components/Loading";
import type { Product, ProductImage } from "~/server/api/routers/shop";

export default function Shop() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const images: ProductImage[] = [
    { id: 1, source: "/tmp/0.jpg", productId: 1 },
    { id: 2, source: "/tmp/1.jpg", productId: 1 },
    { id: 3, source: "/tmp/2.jpg", productId: 1 },
    { id: 4, source: "/tmp/3.jpg", productId: 1 },
  ];

  const product: Product = {
    id: 1,
    title: "Кроссовки",
    subtitle: "Просто кроссовки",
    description: "Эти кроссовки такие кроссовки офигеть просто",
    size: null,
    color: null,
    stock: 10,
    price: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: images,
  };

  const handleCartIconClick = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };

  const { data, isLoading } = api.shop.getAllProducts.useQuery();

  if (isLoading) return <LoadingPage />;
  if (!data) return <div>Что-то пошло не так</div>;

  return (
    <>
      <Head>
        <title>Магазин</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartDrawer isOpen={isDrawerOpen} onCartIconClick={handleCartIconClick} />
      <main className="flex min-h-screen flex-1 flex-col py-24">
        <div className="container grid grid-cols-2 gap-12 md:grid-cols-3 lg:grid-cols-4">
          <ProductCard product={product} />
        </div>
      </main>
    </>
  );
}
