# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      UPLOADTHING_SECRET: ${{secrets.UPLOADTHING_SECRET}}
      UPLOADTHING_APP_ID: ${{secrets.UPLOADTHING_APP_ID}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
      DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
      YANDEX_CLIENT_ID: ${{secrets.YANDEX_CLIENT_ID}}
      YANDEX_CLIENT_SECRET: ${{secrets.YANDEX_CLIENT_SECRET}}
      VK_CLIENT_ID: ${{secrets.VK_CLIENT_ID}}
      VK_CLIENT_SECRET: ${{secrets.VK_CLIENT_SECRET}}
      EMAIL_SERVER: ${{secrets.EMAIL_SERVER}}
      EMAIL_SERVER_USER: ${{secrets.EMAIL_SERVER_USER}}
      EMAIL_SERVER_PASSWORD: ${{secrets.EMAIL_SERVER_PASSWORD}}
      EMAIL_SERVER_HOST: ${{secrets.EMAIL_SERVER_HOST}}
      EMAIL_SERVER_PORT: ${{secrets.EMAIL_SERVER_PORT}}
      EMAIL_FROM: ${{secrets.EMAIL_FROM}}
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
